# Generated by Django 2.2.28 on 2023-05-30 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20230530_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='testworkdatamodel',
        ),
    ]
